[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "TornadoObj"
version = "0.0.12"
description = "Tornado"
authors = [{ name = "Denis Minka", email = "minka.denis@gmail.com" }]
readme = "README.md"
dependencies = ["speeedy", "loguru"]
